#! /bin/bash

nvm_install() {
    curl https://raw.github.com/creationix/nvm/master/install.sh | sh
}

confirm() {
    arg1=$1
    read -r -p "install nvm? [N/y]? " response 
    if [[ $response =~ ^[Yy]$ ]] 
    then
        $1
    else
        echo "Not installing NVM"
        exit 1
    fi
}

#install NVM
if ! [ -d $HOME/.nvm ]; then
    confirm nvm_install
fi
